name: Release
on:
    push:
        tags:
            - 'v*'
jobs:
    release:
        runs-on: ubuntu-latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_FILE: "tooltips.zip"
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              show-progress: true

          - name: Build
            run: make zip FILENAME=${{ env.RELEASE_FILE }}
          
          - name: Create draft release
            run: |
              gh release create \
                --repo ${{ github.repository }} \
                --title ${{ github.ref_name }} \
                --generate-notes \
                ${{ github.ref_name }}

          - name: Upload Docs to GitHub
            run: |
              gh release upload \
                --clobber "${{ github.ref_name }}" \
                --repo ${{ github.repository }} \
                ${{ env.RELEASE_FILE }}
